### ISSUE TITLE
Parse book series page for details

### ISSUE THREAD

**Issue by z33kz33k** [z33kz33k/bookscrape#24]
I need this as a list of Book ID's:
![image](https://github.com/z33kz33k/bookscrape/assets/10428030/5c05ac54-56e7-47db-aeba-8ead78bbacad)

Then, the position of the relevant one would be self-evident and we avoid hassle of trying to make sense of Goodreads treatment of "work" numberings. On the above example it's "BOOK 0.5", "BOOK 1", "BOOK 1.1", "BOOK 2" and so on, but e.g. here:

![image](https://github.com/z33kz33k/bookscrape/assets/10428030/750a8f07-c1f7-497d-9415-d5b0965c9e9a)

it's completely different.

url: `https://www.goodreads.com/series/{book_id}`

### TODO

- [x] parse series ID
- [x] parse series title
- [x] parse numberings
- [x] parse book IDs
- [x] save series ID on the data object
- [x] return None if parsed items are not numbered

This is a subtask of #4
