### ISSUE TITLE
Parse book page's `script` meta tags

### ISSUE THREAD

**Issue by z33kz33k** [z33kz33k/bookscrape#30]
Book page source contains interesting meta `script` tags with easy access to some interesting data (main edition details, awards, genres, characters, places and so on). 

I need to look into it.

#### Notes
The second (bigger) dict (`soup.find("script", id="__NEXT_DATA__")`) has some interesting tidbits under `props/pageProps/apolloState/`:
* `Work:kca://`:
    *  ratings distribution (with reviews language based distribution) under `stats`:
    ![image](https://github.com/z33kz33k/bookscrape/assets/10428030/031bc807-3f15-4e53-80a8-6b2367766fdd)
    * awards, places and characters under `details`:
    ![image](https://github.com/z33kz33k/bookscrape/assets/10428030/d5e6c8c8-7538-4abd-8290-d7015d4dd53b)
* `Book:kca://`:
    * main edition data under `details`:
    ![image](https://github.com/z33kz33k/bookscrape/assets/10428030/d649ce44-6221-46ea-b51f-0f26c5e94ebf)
    * genres data under `bookGenres`:
    ![image](https://github.com/z33kz33k/bookscrape/assets/10428030/9a3eb9b4-bbc4-481f-86f9-b47691a02cf6)
    * description blurb under `'description({"stripped":true})'`
    * full title (that includes series in parentheses) under `titleComplete`: 
![image](https://github.com/z33kz33k/bookscrape/assets/10428030/ad26e0df-dc89-41b9-b1d9-ca6808dabb8d)

I guess, this needs **a separate class** and a bunch of subtasks.

- [x] Book:
    - [x] full title
    - [x] description blurb
    - [x] main edition data
    - [x] genres data
- [x] Work:
    - [x] ratings distribution:
        - [x] language based review distribution
    - [x] details:
        - [x] original title
        - [x] first publication date
        - [x] awards
        - [x] places
        - [x] characters
 
This is a subtask of #4
